### ISSUE TITLE
History API and Edge v15

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/angular-stackables#13]
Video here:
https://drive.google.com/drive/u/1/folders/0B5ukMTFcdv7QZV8zekNPUnp1MDA (DB only)

The button labelled 'Fresh' on the page is turned on in the components `$onInit` function and turned off by clicking on it (which the test does).

`broken-edge.flv` video shows current behavior in Edge v15.15063 running on Windows 10.  When the modal is closed, the page is effectively refreshed.

`patched.flv` shows expected behavior after commenting out this conditional: https://github.com/digitalbazaar/angular-stackables/blob/master/index.js#L334-L343

The existing code does work properly in chrome, firefox, IE11 and Safari 9.

**Comment by mattcollier** [comment]
I wonder if now might be a good time to be done with this module and use Angular Material Dialogs instead https://material.angularjs.org/latest/demo/dialog

**Comment by dlongley** [comment]
Angular Material Dialogs don't support stacking -- which is our main reason for using this library.

**Comment by mattcollier** [comment]
@dlongley not sure if this gives us the functionality desired...

The `multiple` option is documented here: https://material.angularjs.org/latest/api/service/$mdDialog#mddialog-show-optionsorpreset

And of course, there's a plunkr for that: http://embed.plnkr.co/Ga027OYU5nrkua3JxNRy/

**Comment by mattcollier** [comment]
EDIT, the url provided earlier was temporary...
Than plukr can be run directly in a browser via the `copy url to clipboard` option.

As implemented there, it makes no effort to affect back button behavior.

The document does say that the back button (maybe just on mobile?) *should* cancel the dialog: https://material.io/guidelines/components/dialogs.html#dialogs-behavior

That's not the behavior I'm seeing with that plunkr on chromium.

**Comment by mattcollier** [comment]
@dlongley forget that earlier plunkr, it was old versions of everything and wasn't even using the `multiple` option, here's an updated one: https://embed.plnkr.co/REs0xGk4fFbZzpUmGQaa/
