### ISSUE TITLE
a demo page would be great ...

### ISSUE THREAD

**Issue by ph-hs** [digitalbazaar/angular-stackables#8]
... perhaps on gh-pages ?

**Comment by mattcollier** [comment]
@ph-hs here are some examples on how this module is used:
- https://github.com/digitalbazaar/bedrock-angular-modal/
- https://github.com/digitalbazaar/bedrock-examples/tree/master/basic-modals-example

**Comment by ph-hs** [comment]
Thats great. I'll work it out. I was meaning JFiddle style, or elsewhere on the web. I'm of the opinion that web projects/frameworks/libraries lose 90% of their potential audience by not having a play-with-it style demo.

**Comment by mattcollier** [comment]
Thanks for your interest and comments.  We definitely need more documentation and examples.

**Comment by ph-hs** [comment]
Especially as &lt;dialog&gt; married to Angular is paste-these-few-lines-in solution, and we can snip usage of other, larger, frameworks/libs which come with a cost of ownership :)

**Comment by ph-hs** [comment]
OK - got caught out on the 'etc/hosts' step that I'd skipped, but circled back, did a proper RTFM, and was able to interact with the demo. Nice stuff. Can you expand https://github.com/digitalbazaar/bedrock-examples/tree/master/basic-modals-example to show some JavaScript in addition to the the HTML fragments ... there's so much left unsaid.
